### ISSUE TITLE
`U256` and other variants don't respect zero padding in hex formatting

### ISSUE THREAD

**Issue by xJonathanLEI** [paritytech/parity-common#616] opened 2022-01-27 15:49 UTC
In the `LowerHex` implementation, `latch` is only triggered when the first non-zero nibble is reached, ignoring any requested zero padding.

For example, with:

```rust
println!("{:064x}", U256::zero());
```

The expected output is 64 zeros, while the actual output is only 1 zero.

I have a modified implementation which respects the padding and behaves as expected. I can submit a PR with relevant tests, but before I do, I wanna make sure this "fix" is actually wanted (as in, this "ignoring padding" is not done by design). Thanks.

**Comment by ordian** [comment] 2022-01-27 15:51
Thanks for the report. Is this issue duplicate of #584 which is fixed by #603?

**Comment by xJonathanLEI** [comment] 2022-01-27 16:02
That was quick! Thanks!

I looked at the linked PR and it does seem to solve it. However, I just ran this with the latest `master` and got `1` and `0` as output:

```rust
use primitive_types::U256;

fn main() {
    println!("{:064x}", U256::one());
    println!("{:064x}", U256::zero());
}
```

So I guess there's a regression or something?

**Comment by ordian** [comment] 2022-01-27 16:03
We haven't merged that PR in `master` yet. Waiting for another approval...

**Comment by ordian** [comment] 2022-01-27 16:05
closing as duplicate of #584

**Closed by ordian** 2022-01-27 16:05 UTC
